In [1]:
import pandas as pd

In [6]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import time

def get_location_info(latitude, longitude):
    geolocator = Nominatim(user_agent="my_agent")
    tries = 0
    while tries < 3:
        try:
            # Ensure the coordinates are floats and in the correct format
            lat = float(latitude)
            lon = float(longitude)
            location = geolocator.reverse(f"{lat}, {lon}")
            if location:
                address = location.raw['address']
                country = address.get('country', 'Unknown')
                county = address.get('county', 'Unknown')
                return country, county
            else:
                return 'Unknown', 'Unknown'
        except (GeocoderTimedOut, GeocoderServiceError):
            tries += 1
            time.sleep(1)
        except ValueError:
            print(f"Invalid coordinates: Latitude={latitude}, Longitude={longitude}")
            return 'Invalid', 'Invalid'
    return 'Unknown', 'Unknown'

# Load the dataset
df = pd.read_csv("/content/monarch_data_2024_fall_20241005_125900 (1).csv")

# Create new columns for country and county
df['Country'] = ''
df['County'] = ''

# Iterate through the DataFrame and update country and county
for index, row in df.iterrows():
    try:
        latitude = float(row['Latitude'])
        longitude = float(row['Longitude'])
        country, county = get_location_info(latitude, longitude)
        df.at[index, 'Country'] = country
        df.at[index, 'County'] = county
    except ValueError:
        print(f"Invalid data in row {index}: Latitude={row['Latitude']}, Longitude={row['Longitude']}")
        df.at[index, 'Country'] = 'Invalid'
        df.at[index, 'County'] = 'Invalid'

    # Print progress
    if index % 10 == 0:
        print(f"Processed {index} rows")

# Save the updated DataFrame
df.to_csv('updated_dataset.csv', index=False)

print("Processing complete. Updated dataset saved as 'updated_dataset.csv'")

Processed 0 rows
Processed 10 rows
Processed 20 rows
Processed 30 rows
Processed 40 rows
Processed 50 rows
Processed 60 rows
Processed 70 rows
Processed 80 rows
Processed 90 rows
Processed 100 rows
Processed 110 rows
Processed 120 rows
Processed 130 rows
Processed 140 rows
Processed 150 rows
Processed 160 rows
Processed 170 rows
Processed 180 rows
Processed 190 rows
Processed 200 rows

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=42.4&lon=-72.5&format=json&addressdetails=1

Processed 210 rows
Processing complete. Updated dataset saved as 'updated_dataset.csv'

In [3]:
df

,Date,Town,State/Province,Latitude,Longitude,Number,Image,Country,County
0,NaN,Date,Town,State/Province,Latitude,Longitude,NaN,Invalid,Invalid
1,1.0,10/26/24,Rockbridge,OH,39.6,-82.5,NaN,Invalid,Invalid
2,2.0,10/05/24,Nashville,IL,38.4,-89.5,NaN,Invalid,Invalid
3,3.0,10/04/24,Rockbridge,OH,39.6,-82.5,NaN,Invalid,Invalid
4,4.0,10/04/24,Tulsa,OK,36.1,-96,NaN,Invalid,Invalid
...,...,...,...,...,...,...,...,...,...
207,207.0,08/01/24,Dallas,TX,32.7,-96.8,NaN,Invalid,Invalid
208,208.0,08/01/24,Pasadena,MD,39.1,-76.5,NaN,Invalid,Invalid
209,209.0,08/01/24,Vancouver,WA,45.6,-122.5,NaN,Invalid,Invalid
210,210.0,08/01/24,Tulsa,OK,36.1,-96,NaN,Invalid,Invalid
211,211.0,08/01/24,Emmaus,PA,40.5,-75.5,NaN,Invalid,Invalid

In [5]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import time

def get_location_info(state, longitude):
    geolocator = Nominatim(user_agent="my_agent")
    tries = 0
    while tries < 3:
        try:
            # Use the state abbreviation and longitude to approximate location
            location = geolocator.geocode(f"{state}, United States")
            if location:
                # Use the found latitude and the given longitude
                precise_location = geolocator.reverse(f"{location.latitude}, {longitude}")
                if precise_location:
                    address = precise_location.raw['address']
                    country = address.get('country', 'United States')
                    county = address.get('county', address.get('state_district', 'Unknown'))
                    return country, county
                else:
                    return 'United States', state
            else:
                return 'United States', 'Unknown'
        except (GeocoderTimedOut, GeocoderServiceError):
            tries += 1
            time.sleep(1)
        except ValueError as e:
            print(f"Error processing location: State={state}, Longitude={longitude}. Error: {str(e)}")
            return 'Invalid', 'Invalid'
    return 'Timeout', 'Timeout'

# Load the dataset


print("First few rows of the dataset:")
print(df.head())
print("\nColumn names:")
print(df.columns)

# Create new columns for country and county if they don't exist
if 'Country' not in df.columns:
    df['Country'] = ''
if 'County' not in df.columns:
    df['County'] = ''

# Iterate through the DataFrame and update country and county
for index, row in df.iterrows():
    try:
        state = row['Latitude']  # Using 'Latitude' column for state abbreviation
        longitude = row['Longitude']
        print(f"Processing row {index}: State={state}, Longitude={longitude}")
        country, county = get_location_info(state, longitude)
        df.at[index, 'Country'] = country
        df.at[index, 'County'] = county
    except KeyError as e:
        print(f"Error in row {index}: Missing column {str(e)}")
        df.at[index, 'Country'] = 'Missing Data'
        df.at[index, 'County'] = 'Missing Data'
    except Exception as e:
        print(f"Unexpected error in row {index}: {str(e)}")
        df.at[index, 'Country'] = 'Error'
        df.at[index, 'County'] = 'Error'

    # Print progress
    if index % 10 == 0 and index > 0:
        print(f"Processed {index} rows")

# Save the updated DataFrame
df.to_csv('updated_dataset.csv', index=False)

print("\nProcessing complete. Updated dataset saved as 'updated_dataset.csv'")
print("\nFirst few rows of the updated dataset:")
print(df.head())

First few rows of the dataset:
   Date      Town State/Province        Latitude Longitude     Number  Image  \
0   NaN      Date           Town  State/Province  Latitude  Longitude    NaN
1   1.0  10/26/24     Rockbridge              OH      39.6      -82.5    NaN
2   2.0  10/05/24      Nashville              IL      38.4      -89.5    NaN
3   3.0  10/04/24     Rockbridge              OH      39.6      -82.5    NaN
4   4.0  10/04/24          Tulsa              OK      36.1        -96    NaN

   Country   County
0  Invalid  Invalid
1  Invalid  Invalid
2  Invalid  Invalid
3  Invalid  Invalid
4  Invalid  Invalid

Column names:
Index(['Date', 'Town', 'State/Province', 'Latitude', 'Longitude', 'Number',
       'Image', 'Country', 'County'],
      dtype='object')
Processing row 0: State=State/Province, Longitude=Latitude
Error processing location: State=State/Province, Longitude=Latitude. Error: Must be a coordinate pair or Point
Processing row 1: State=OH, Longitude=39.6
Processing row 2: State=IL, Longitude=38.4
Processing row 3: State=OH, Longitude=39.6
Processing row 4: State=OK, Longitude=36.1
Processing row 5: State=SC, Longitude=33.6
Processing row 6: State=NS, Longitude=44.7
Processing row 7: State=SC, Longitude=33.6
Processing row 8: State=PA, Longitude=40.4
Processing row 9: State=TX, Longitude=30.8
Processing row 10: State=UT, Longitude=40.4
Processed 10 rows
Processing row 11: State=KY, Longitude=38.2
Processing row 12: State=MN, Longitude=44.9
Processing row 13: State=NY, Longitude=43
Processing row 14: State=NH, Longitude=43.7
Processing row 15: State=WI, Longitude=44
Processing row 16: State=TX, Longitude=33.1
Processing row 17: State=TX, Longitude=30.8
Processing row 18: State=MO, Longitude=38.2
Processing row 19: State=MN, Longitude=44
Processing row 20: State=TX, Longitude=32.8
Processed 20 rows
Processing row 21: State=OK, Longitude=35.5
Processing row 22: State=OK, Longitude=35.9
Processing row 23: State=MD, Longitude=39
Processing row 24: State=MA, Longitude=42.5
Processing row 25: State=OK, Longitude=35.5
Processing row 26: State=VA, Longitude=37.5
Processing row 27: State=VA, Longitude=37.5
Processing row 28: State=OK, Longitude=35.5
Processing row 29: State=CA, Longitude=39.2
Processing row 30: State=ON, Longitude=48.1
Processed 30 rows
Processing row 31: State=IL, Longitude=38.4
Processing row 32: State=PA, Longitude=39.9
Processing row 33: State=NS, Longitude=44.5
Processing row 34: State=MN, Longitude=44
Processing row 35: State=SC, Longitude=32.7
Processing row 36: State=ME, Longitude=44.4
Processing row 37: State=ME, Longitude=43.1
Processing row 38: State=KS, Longitude=39
Processing row 39: State=WI, Longitude=44.6
Processing row 40: State=WI, Longitude=42.9
Processed 40 rows
Processing row 41: State=OK, Longitude=33.9
Processing row 42: State=OH, Longitude=41.5
Processing row 43: State=MN, Longitude=44.9
Processing row 44: State=OK, Longitude=33.9
Processing row 45: State=NJ, Longitude=39.5
Processing row 46: State=MN, Longitude=44
Processing row 47: State=VA, Longitude=37.3
Processing row 48: State=VA, Longitude=38.1
Processing row 49: State=SC, Longitude=32.4
Processing row 50: State=ON, Longitude=41.9
Processed 50 rows
Processing row 51: State=OK, Longitude=33.9
Processing row 52: State=NS, Longitude=45.2
Processing row 53: State=TN, Longitude=35.7
Processing row 54: State=OK, Longitude=35.6
Processing row 55: State=UT, Longitude=41.3
Processing row 56: State=MD, Longitude=39.1
Processing row 57: State=PA, Longitude=39.9
Processing row 58: State=NS, Longitude=44.4
Processing row 59: State=ON, Longitude=44.4
Processing row 60: State=UT, Longitude=38.9
Processed 60 rows
Processing row 61: State=WI, Longitude=42.9
Processing row 62: State=MO, Longitude=39.7
Processing row 63: State=IA, Longitude=41.6
Processing row 64: State=NJ, Longitude=41
Processing row 65: State=NE, Longitude=41.5
Processing row 66: State=NC, Longitude=36.1
Processing row 67: State=FL, Longitude=27.8
Processing row 68: State=MD, Longitude=39
Processing row 69: State=MD, Longitude=39
Processing row 70: State=KS, Longitude=39
Processed 70 rows
Processing row 71: State=ON, Longitude=44.4
Processing row 72: State=ME, Longitude=44.3
Processing row 73: State=NJ, Longitude=41.1
Processing row 74: State=MN, Longitude=46.4
Processing row 75: State=IN, Longitude=39.7
Processing row 76: State=OK, Longitude=35.5
Processing row 77: State=OK, Longitude=34.8
Processing row 78: State=MI, Longitude=42.4
Processing row 79: State=NS, Longitude=44.6
Processing row 80: State=OH, Longitude=41.5
Processed 80 rows
Processing row 81: State=SC, Longitude=32.7
Processing row 82: State=PA, Longitude=39.9
Processing row 83: State=NS, Longitude=44.1
Processing row 84: State=NY, Longitude=41.5
Processing row 85: State=MI, Longitude=44.6
Processing row 86: State=IN, Longitude=39.8
Processing row 87: State=AZ, Longitude=35.2
Processing row 88: State=KS, Longitude=38.9
Processing row 89: State=MI, Longitude=43.1
Processing row 90: State=WI, Longitude=43
Processed 90 rows
Processing row 91: State=MN, Longitude=43.7
Processing row 92: State=MN, Longitude=46.5
Processing row 93: State=TN, Longitude=36
Processing row 94: State=NY, Longitude=41.5
Processing row 95: State=NY, Longitude=42.8
Processing row 96: State=TX, Longitude=33
Processing row 97: State=MD, Longitude=39
Processing row 98: State=MN, Longitude=43.5
Processing row 99: State=SC, Longitude=32.7
Processing row 100: State=TX, Longitude=30.7
Processed 100 rows
Processing row 101: State=IN, Longitude=40
Processing row 102: State=IL, Longitude=40.8
Processing row 103: State=SD, Longitude=43.5
Processing row 104: State=NH, Longitude=43
Processing row 105: State=FL, Longitude=27.8
Processing row 106: State=OH, Longitude=39.3
Processing row 107: State=OK, Longitude=35.2
Processing row 108: State=SC, Longitude=32.7
Processing row 109: State=ON, Longitude=45.9
Processing row 110: State=ON, Longitude=43.7
Processed 110 rows
Processing row 111: State=WI, Longitude=43.3
Processing row 112: State=IN, Longitude=41.6
Processing row 113: State=MA, Longitude=42.1
Processing row 114: State=PA, Longitude=41.5
Processing row 115: State=IL, Longitude=39.6
Processing row 116: State=MO, Longitude=39.8
Processing row 117: State=CT, Longitude=41.8
Processing row 118: State=MD, Longitude=39.3
Processing row 119: State=KS, Longitude=39.3
Processing row 120: State=OK, Longitude=35.2
Processed 120 rows
Processing row 121: State=GA, Longitude=34.9
Processing row 122: State=MS, Longitude=31.5
Processing row 123: State=OK, Longitude=36.1
Processing row 124: State=OK, Longitude=36.1
Processing row 125: State=NY, Longitude=42.8
Processing row 126: State=NY, Longitude=43.2
Processing row 127: State=OK, Longitude=36.1
Processing row 128: State=NC, Longitude=35.4
Processing row 129: State=NC, Longitude=35.4
Processing row 130: State=MI, Longitude=44.4
Processed 130 rows
Processing row 131: State=PA, Longitude=41.1
Processing row 132: State=NJ, Longitude=41
Processing row 133: State=IN, Longitude=37.9
Processing row 134: State=WI, Longitude=42.6
Processing row 135: State=MN, Longitude=46.4
Processing row 136: State=WI, Longitude=44.2
Processing row 137: State=CT, Longitude=41.8
Processing row 138: State=MA, Longitude=41.6
Processing row 139: State=MD, Longitude=38.4
Processing row 140: State=IL, Longitude=42.4
Processed 140 rows
Processing row 141: State=OH, Longitude=41.1
Processing row 142: State=NJ, Longitude=40.9
Processing row 143: State=FL, Longitude=28.4
Processing row 144: State=CT, Longitude=41.5
Processing row 145: State=WI, Longitude=46.1
Processing row 146: State=KY, Longitude=38.2
Processing row 147: State=ME, Longitude=43.8
Processing row 148: State=KY, Longitude=38.2
Processing row 149: State=SK, Longitude=51.4
Processing row 150: State=NJ, Longitude=40.9
Processed 150 rows
Processing row 151: State=CA, Longitude=38.1
Processing row 152: State=TX, Longitude=31.7
Processing row 153: State=PA, Longitude=41.5
Processing row 154: State=NJ, Longitude=40.9

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=40.0757384&lon=40.9&format=json&addressdetails=1

Processing row 155: State=TX, Longitude=29.7
Processing row 156: State=PA, Longitude=40.4
Processing row 157: State=MI, Longitude=43
Processing row 158: State=ME, Longitude=44.3
Processing row 159: State=NY, Longitude=41.1
Processing row 160: State=MO, Longitude=38.6
Processed 160 rows
Processing row 161: State=NY, Longitude=40.9
Processing row 162: State=PA, Longitude=41.5
Processing row 163: State=NJ, Longitude=39.5
Processing row 164: State=PA, Longitude=40.3
Processing row 165: State=NY, Longitude=42.8
Processing row 166: State=NJ, Longitude=40.9
Processing row 167: State=NY, Longitude=42.8
Processing row 168: State=MA, Longitude=42.6
Processing row 169: State=NY, Longitude=42.8
Processing row 170: State=NH, Longitude=43.9
Processed 170 rows
Processing row 171: State=PA, Longitude=41.1
Processing row 172: State=PA, Longitude=41.1
Processing row 173: State=PA, Longitude=41.1
Processing row 174: State=PA, Longitude=41.1
Processing row 175: State=PA, Longitude=41.2
Processing row 176: State=NE, Longitude=40.6

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=41.7370229&lon=40.6&format=json&addressdetails=1

Processing row 177: State=CA, Longitude=41.8
Processing row 178: State=ME, Longitude=44.3
Processing row 179: State=TX, Longitude=27.8
Processing row 180: State=NJ, Longitude=40.8
Processed 180 rows
Processing row 181: State=NJ, Longitude=40.9
Processing row 182: State=MA, Longitude=42.3
Processing row 183: State=OH, Longitude=41.5
Processing row 184: State=ON, Longitude=45.2
Processing row 185: State=OH, Longitude=41.4
Processing row 186: State=NY, Longitude=42.5
Processing row 187: State=MA, Longitude=42.1
Processing row 188: State=OH, Longitude=39.3
Processing row 189: State=MI, Longitude=42.6
Processing row 190: State=KS, Longitude=38.9
Processed 190 rows
Processing row 191: State=TN, Longitude=36.5
Processing row 192: State=NY, Longitude=43.2
Processing row 193: State=ID, Longitude=43.6
Processing row 194: State=FL, Longitude=28
Processing row 195: State=IL, Longitude=42.2
Processing row 196: State=MN, Longitude=43.9
Processing row 197: State=VA, Longitude=38.9
Processing row 198: State=OK, Longitude=36.1
Processing row 199: State=NJ, Longitude=39.4
Processing row 200: State=NJ, Longitude=39.4

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=40.0757384&lon=39.4&format=json&addressdetails=1

Processed 200 rows
Processing row 201: State=NH, Longitude=43.1
Processing row 202: State=TX, Longitude=27.8
Processing row 203: State=MA, Longitude=42.4
Processing row 204: State=TX, Longitude=29.5
Processing row 205: State=PA, Longitude=41.5
Processing row 206: State=MB, Longitude=50.2
Processing row 207: State=TX, Longitude=32.7
Processing row 208: State=MD, Longitude=39.1
Processing row 209: State=WA, Longitude=45.6
Processing row 210: State=OK, Longitude=36.1
Processed 210 rows
Processing row 211: State=PA, Longitude=40.5

Processing complete. Updated dataset saved as 'updated_dataset.csv'

First few rows of the updated dataset:
   Date      Town State/Province        Latitude Longitude     Number  Image  \
0   NaN      Date           Town  State/Province  Latitude  Longitude    NaN
1   1.0  10/26/24     Rockbridge              OH      39.6      -82.5    NaN
2   2.0  10/05/24      Nashville              IL      38.4      -89.5    NaN
3   3.0  10/04/24     Rockbridge              OH      39.6      -82.5    NaN
4   4.0  10/04/24          Tulsa              OK      36.1        -96    NaN

   Country   County
0  Invalid  Invalid
1  Türkiye  Unknown
2  Türkiye  Unknown
3  Türkiye  Unknown
4    سوريا  Unknown

In [7]:
df

,Unnamed: 0,Date,Town,State/Province,Latitude,Longitude,Country,County
0,1,10/26/2024,Rockbridge,OH,39.6,-82.5,United States,Hocking County
1,2,10/5/2024,Nashville,IL,38.4,-89.5,United States,Washington County
2,3,10/4/2024,Rockbridge,OH,39.6,-82.5,United States,Hocking County
3,4,10/4/2024,Tulsa,OK,36.1,-96.0,United States,Tulsa County
4,5,10/3/2024,Murrells Inlet,SC,33.6,-79.1,United States,Georgetown County
...,...,...,...,...,...,...,...,...
206,207,8/1/2024,Dallas,TX,32.7,-96.8,United States,Dallas County
207,208,8/1/2024,Pasadena,MD,39.1,-76.5,United States,Anne Arundel County
208,209,8/1/2024,Vancouver,WA,45.6,-122.5,United States,Clark County
209,210,8/1/2024,Tulsa,OK,36.1,-96.0,United States,Tulsa County
210,211,8/1/2024,Emmaus,PA,40.5,-75.5,United States,Lehigh County

In [11]:
df1

,Date,Town,State/Province,Latitude,Longitude,Number,Image,Country,County
0,NaN,Date,Town,State/Province,Latitude,Longitude,NaN,Timeout,Timeout
1,1.0,12/26/10,Angangueo,MIC,20,-100,NaN,Timeout,Timeout
2,2.0,12/23/10,Santa Barbara,CA,34.4,-119.7,NaN,Timeout,Timeout
3,3.0,12/19/10,Rosenberg,TX,29.5,-95.9,NaN,United States,Shawnee County
4,4.0,12/17/10,houma,LA,29.6,-90.8,NaN,Timeout,Timeout
...,...,...,...,...,...,...,...,...,...
652,652.0,01/10/10,Fenwick,MI,43.1,-85.1,NaN,,
653,653.0,01/09/10,New Orleans,LA,30,-90.1,NaN,,
654,654.0,01/04/10,Taylor Lake Village,TX,29.6,-95.1,NaN,,
655,655.0,01/04/10,Marigot,Collectivity of Saint Martin,18.1,-63.1,NaN,,
656,656.0,01/01/10,ST. PETERSBURG,FL,27.8,-82.6,NaN,,

In [ ]:
import pandas as pd
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderServiceError
import time

def get_location_info(state, longitude):
    geolocator = Nominatim(user_agent="my_agent")
    tries = 0
    while tries < 3:
        try:
            # Use the state abbreviation and longitude to approximate location
            location = geolocator.geocode(f"{state}, United States")
            if location:
                # Use the found latitude and the given longitude
                precise_location = geolocator.reverse(f"{location.latitude}, {longitude}")
                if precise_location:
                    address = precise_location.raw['address']
                    country = address.get('country', 'United States')
                    county = address.get('county', address.get('state_district', 'Unknown'))
                    return country, county
                else:
                    return 'United States', state
            else:
                return 'United States', 'Unknown'
        except (GeocoderTimedOut, GeocoderServiceError):
            tries += 1
            time.sleep(1)
        except ValueError as e:
            print(f"Error processing location: State={state}, Longitude={longitude}. Error: {str(e)}")
            return 'Invalid', 'Invalid'
    return 'Timeout', 'Timeout'

# Load the dataset
df1 = pd.read_csv("/content/monarch_data_2010_all_seasons_20241005_125900.csv")

print("First few rows of the dataset:")
print(df1.head())
print("\nColumn names:")
print(df1.columns)

# Create new columns for country and county if they don't exist
if 'Country' not in df1.columns:
    df1['Country'] = ''
if 'County' not in df1.columns:
    df1['County'] = ''

# Iterate through the DataFrame and update country and county
for index, row in df.iterrows():
    try:
        state = row['Latitude']  # Using 'Latitude' column for state abbreviation
        longitude = row['Longitude']
        print(f"Processing row {index}: State={state}, Longitude={longitude}")
        country, county = get_location_info(state, longitude)
        df1.at[index, 'Country'] = country
        df1.at[index, 'County'] = county
    except KeyError as e:
        print(f"Error in row {index}: Missing column {str(e)}")
        df1.at[index, 'Country'] = 'Missing Data'
        df1.at[index, 'County'] = 'Missing Data'
    except Exception as e:
        print(f"Unexpected error in row {index}: {str(e)}")
        df1.at[index, 'Country'] = 'Error'
        df1.at[index, 'County'] = 'Error'

    # Print progress
    if index % 10 == 0 and index > 0:
        print(f"Processed {index} rows")

# Save the updated DataFrame
df1.to_csv('updated_dataset_2010.csv', index=False)

print("\nProcessing complete. Updated dataset saved as 'updated_dataset.csv'")
print("\nFirst few rows of the updated dataset:")
print(df1.head())

First few rows of the dataset:
   Date      Town State/Province        Latitude Longitude     Number  Image
0   NaN      Date           Town  State/Province  Latitude  Longitude    NaN
1   1.0  12/26/10      Angangueo             MIC        20       -100    NaN
2   2.0  12/23/10  Santa Barbara              CA      34.4     -119.7    NaN
3   3.0  12/19/10      Rosenberg              TX      29.5      -95.9    NaN
4   4.0  12/17/10          houma              LA      29.6      -90.8    NaN

Column names:
Index(['Date', 'Town', 'State/Province', 'Latitude', 'Longitude', 'Number',
       'Image'],
      dtype='object')
Processing row 0: State=39.6, Longitude=-82.5

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1

Processing row 1: State=38.4, Longitude=-89.5

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=38.4%2C+United+States&format=json&limit=1

Processing row 2: State=39.6, Longitude=-82.5

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=39.6%2C+United+States&format=json&limit=1

Processing row 3: State=36.1, Longitude=-96.0
Processing row 4: State=33.6, Longitude=-79.1

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1

Processing row 5: State=44.7, Longitude=-63.5

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=44.7%2C+United+States&format=json&limit=1

Processing row 6: State=33.6, Longitude=-79.0

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=33.6%2C+United+States&format=json&limit=1